Set permission to the delegation
moesaeed/PCOCGraphQL pull request #16
Opened 2024-07-17 07:59 UTC by FarhanIrani1

2024-07-17 19:01 UTC, moesaeed commented on DF2023/Core/Custom/DelegationManager.cs
> +                    SetPermission(item, user.Id);
Could you add a role called "PCOC" as well in order for the admin to view/update/delete the item as well? @FarhanIrani1

2024-07-17 19:48 UTC, moesaeed requested changes

2024-07-18 21:59 UTC, FarhanIrani1 commented on DF2023/Core/Custom/DelegationManager.cs
> +                    SetPermission(item, user.Id);
done

2024-07-18 21:59 UTC, FarhanIrani1 commented on DF2023/WebPageHelper/CommonHelper.cs
> +            //var token = "Yjk3Mzg4OGEtMWRhYy00ZDU2LWJlMmMtZTZkZjc2NDJkMGZlLT1wcm92aWRlcj0tRGVmYXVsdC09c2VjcmV0a2V5PS1ZeT1YYm1UUV5LdTorbnRhQ3Z7PlB3SHR4bHRYJVFoTTtTbUpXYkA+cFBTRVMhVS1uUjRbU01NRUgvaFJO
done

2024-07-19 03:08 UTC, moesaeed approved these changes

2024-07-19 03:08 UTC, merged